import { Server, Cloud, Network } from 'lucide-react';

const About = () => {
    return (
      <div className="container mx-auto px-4">
        <div className="mb-14 text-center">
          <span className="inline-block px-3 py-1 text-sm font-medium text-blue-800 bg-blue-100 rounded-full mb-3">About the Conference</span>
          <h2 className="text-3xl md:text-4xl font-bold text-gray-900">ICFEC 2026</h2>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-12">
          <div className="bg-white shadow-md rounded-xl p-6 hover:shadow-lg transition-shadow">
            <div className="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center mb-4">
              <Server className="text-blue-600" />
            </div>
            <h3 className="text-xl font-semibold mb-3 text-gray-900">Edge Computing</h3>
            <p className="text-gray-600">
              Exploring the latest advancements in edge computing architectures and systems that bring computation closer to data sources.
            </p>
          </div>
          
          <div className="bg-white shadow-md rounded-xl p-6 hover:shadow-lg transition-shadow">
            <div className="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center mb-4">
              <Cloud className="text-blue-600" />
            </div>
            <h3 className="text-xl font-semibold mb-3 text-gray-900">Fog Computing</h3>
            <p className="text-gray-600">
              Investigating fog computing paradigms that extend cloud computing capabilities to the edge of the network for improved efficiency.
            </p>
          </div>
          
          <div className="bg-white shadow-md rounded-xl p-6 hover:shadow-lg transition-shadow">
            <div className="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center mb-4">
              <Network className="text-blue-600" />
            </div>
            <h3 className="text-xl font-semibold mb-3 text-gray-900">IoT Integration</h3>
            <p className="text-gray-600">
              Addressing challenges in connecting billions of IoT devices while maintaining performance and real-time operations.
            </p>
          </div>
        </div>
        
        <div className="max-w-4xl mx-auto bg-white p-8 rounded-xl shadow-md">
          <p className="text-gray-700 mb-6 leading-relaxed">
            Billions of devices and sensors ranging from user gadgets to more complex systems with sensing and actuating capabilities, such as power 
            grids or vehicles, from the physical world are getting connected to the Internet. However, the need to operate the scale of heterogeneous 
            devices and sensors while being performance-efficient in real-time is challenging. Typically, the data generated by the devices and sensors 
            are transferred to and processed centrally by services hosted on geographically distant clouds. This is untenable given the communication 
            latency incurred and the ingress bandwidth demand.
          </p>
          <p className="text-gray-700 mb-6 leading-relaxed">
            A new and disruptive paradigm spear-headed by academics and industry experts is taking shape so that applications can leverage 
            resources located at the edge of the network and along the continuum between the cloud and the edge. These edge resources may be 
            geographically or in the network topology be closer to devices and sensors, such as home router, gateways or more substantial micro data 
            centres. Edge resources may be used to offload selected services from the cloud to accelerate an application or host edge-native 
            applications. The paradigm within which the edge is harnessed is referred to as 'Fog/Edge computing'.
          </p>
          <p className="text-gray-700 leading-relaxed">
            The Fog/Edge computing paradigm is expected to improve the agility of service deployments, make use of opportunistic and cheap 
            computing, and leverage the network latency and bandwidth diversities between these resources. Numerous challenges arise when using 
            edge resources, which requires the re-examination of operating systems, virtualization and containers, and middleware techniques for fabric 
            management. Extensions to current programming and storage models are required and new abstractions that will allow developers to 
            design novel applications that can benefit from massively distributed and data-driven systems need to be developed.
          </p>
        </div>
      </div>
    );
  };

export default About;